const SachTonGiao = [
  {
    title: 'Giận',
    image: require('../../assets/Books/TonGiao/gian.jpg'),
    author: 'Thích Nhất Hạnh',
    type: 'Tôn Giáo',
    desc: 'Giận là một cuốn sách hay của Thiền sư Thích Nhất Hạnh, nó mở ra cho ta những khả năng kỳ diệu, nhưng lại rất dễ thực hành để ta tự mình từng bước... thoát khỏi cơn giận và sống đẹp với xã hội quanh mình.',
    status: 'Hoàn Thành',
  },
  {
    title: 'Giọt Nước Cành Dương',
    image: require('../../assets/Books/TonGiao/giotnuoccanhduong.jpg'),
    author: 'Thích Nhất Hạnh',
    type: 'Tôn Giáo',
    desc: 'Vẫn với văn phong giản dị, Giọt Nước Cành Dương mang đến cho người đọc 15 mẩu chuyện đời thường nhưng mang đậm triết lý Phật giáo. Từ những câu chuyện xoay quanh đời sống tu hành của nhân vật Tôi cho đến những câu chuyện cổ tích và đời thường giản dị dễ hiểu nhưng hàm chứa triết lý sâu sắc, uyên thâm.',
    status: 'Hoàn Thành',
  },
  {
    title: 'Nhật Tụng Thiền Môn',
    image: require('../../assets/Books/TonGiao/nhattungthienmon.jpg'),
    author: 'Thích Nhất Hạnh',
    type: 'Tôn Giáo',
    desc: 'Đã từ năm mươi năm nay, Phật tử Việt Nam, nhất là giới xuất gia, chờ đợi một cuốn Nhật Tụng Thiền Môn bằng Quốc Ngữ. Trong quá trình thực tập và hoằng pháp, tôi cũng đã từng nhiều lần cảm thấy nhu yếu cấp thiết này. Nay sách Nhật Tụng Thiền Môn của Đạo Tràng Mai Thôn được ấn hành, tôi hết sức vui mừng và xin trân trọng giới thiệu với các giới hành giả khắp nơi trong toàn quốc.',
    status: 'Hoàn Thành',
  },
  {
    title: 'Tình Thầy',
    image: require('../../assets/Books/TonGiao/tinhthay.jpg'),
    author: 'Thích Nhất Hạnh',
    type: 'Tôn Giáo',
    desc: 'Cuốn sách ghi lại những khoảnh khắc gần gũi, niềm vui và hạnh phúc mà tác giả có được với thầy mình: Thiền sư Thích Nhất Hạnh',
    status: 'Hoàn Thành',
  },
  {
    title: 'Tri Kỷ Của Bụt',
    image: require('../../assets/Books/TonGiao/trikycuabut.jpg'),
    author: 'Thích Nhất Hạnh',
    type: 'Tôn Giáo',
    desc: 'Chúng ta có phải là tri kỷ của Bụt không? Chúng ta có hiểu được Bụt không? Thật ra người ta đã hiểu lầm Bụt rất nhiều. Không phải chỉ những người ngoài đạo Bụt mà ngay trong chính hàng đệ tử của Bụt cũng hiểu lầm Bụt. Bụt không dạy như vậy nhưng người ta nói Bụt dạy như vậy, rất oan cho Bụt. Ta hiểu lầm Bụt, rồi truyền đạt giáo lý của Bụt một cách sai lạc và kéo theo sự hiểu lầm của cả thế hệ tương lai. ',
    status: 'Hoàn Thành',
  },
  {
    title: 'Thương Yêu Theo Phương Pháp Bụt Dạy',
    image: require('../../assets/Books/TonGiao/thuongyeu.jpg'),
    author: 'Thích Nhất Hạnh',
    type: 'Tôn Giáo',
    desc: 'Thương Yêu Theo Phương Pháp Bụt Dạy Khi nói đến thương yêu, ta hay nghĩ rằng đối tượng thương yêu là một người khác. Từ nhỏ chúng ta cũng được dạy rằng phải yêu thương người khác, thậm chí đến quên mình, đó được ca ngợi là đức hy sinh. Nhưng Bụt dạy rằng đối tượng thương yêu đầu tiên...',
    status: 'Hoàn Thành',
  },
  {
    title: 'Người Vô Sự',
    image: require('../../assets/Books/TonGiao/nguoivosu.jpg'),
    author: 'Thích Nhất Hạnh',
    type: 'Tôn Giáo',
    desc: 'Người Vô Sự "Tuệ giác không phải là kiến thức khái niệm. Tuệ giác có khả năng mang tới sống động và tư do trong giấy phút hiện tại. Kiến thức không làm được việc ấy." Cuốn sách gồm hai phần chính: Phần "Lâm Tế Lục" và phần bình giảng của Thiền sư...',
    status: 'Hoàn Thành',
  },
  {
    title: 'An Nhiên Giữa Những Thăng Trầm',
    image: require('../../assets/Books/TonGiao/annhien.jpg'),
    author: 'Như Nhiên Thích Tánh Tuệ',
    type: 'Tôn Giáo',
    desc: 'Ai trong đời chẳng từng một lần rơi vào tận cùng nỗi cô đơn, chợt thấy mình yếu đuối, mong manh quá đỗi; chẳng từng một lần chực gục ngã, buông xuôi trong bão giông cuộc đời; chẳng từng một lần chán nản trước thế sự đổi thay, lòng người nguội lạnh; chẳng từng một lần cảm thấy tìm chút bình an trong cuộc đời vô thường sao khó quá…',
    status: 'Hoàn Thành',
  },
  {
    title: 'Đường Mây Trên Đất Hoa',
    image: require('../../assets/Books/TonGiao/duongmay.jpg'),
    author: 'Thích Hằng Đạt',
    type: 'Tôn Giáo',
    desc: 'Phần lớn các thiền sư đều ra đi không để lại dấu vết, nếu có thì chỉ lưu lại một vài giai thoại sơ lược nên rất ít ai biết rõ công phu tu tập của các ngài. Có lẽ biết rõ chúng sanh thời Mạt pháp nghiệp dày, trí mỏng, tín tâm yếu kém nên một vài thiền sư đã để lại tài liệu tu tập như một chứng...',
    status: 'Hoàn Thành',
  },
  {
    title: 'Trí Tuệ Của Sự Từ Bi',
    image: require('../../assets/Books/TonGiao/trituetubi.jpg'),
    author: 'Đức Đạt-lai Lạt-ma',
    type: 'Tôn Giáo',
    desc: 'Nghiên cứu mới nhất trong khoa học thần kinh cho thấy rằng khi lòng từ bi có ở trong tâm trí chúng ta, nhiệt thành quan tâm về hạnh phúc, sự đau khổ, nỗi buồn của người khác, tinh thần cũng tăng một cách đáng kể. Đây được coi là dấu hiệu cho thấy những xúc cảm tích cực biểu hiện qua cảm xúc, sự nhiệt tình, lòng từ bi đang chảy trong người.',
    status: 'Hoàn Thành',
  },
]

export default SachTonGiao
