const SachKyNang = [
    {
        title: "100 Cách Sống Hạnh Phúc",
        image: require('../../assets/Books/KyNang/100cach.jpg'),
        author: "Timothy J. Sharp",
        type: 'Kỹ Năng',
        desc: 'Trong quyển sách bổ ích và đầy cảm hứng này, Dr. Timothy J. Sharp chia sẽ 100 động cơ nâng đỡ tinh thần, có thể thực hành một cách nhẹ nhàng mỗi ngày và mang lại cho bạn những kết quả tốt đẹp, làm thay đổi cuộc đời về sau.',
        status: 'Hoàn Thành',
    },
    {
        title: "Biên Niên Ký Thất Nghiệp",
        image: require('../../assets/Books/KyNang/biennienky.jpg'),
        author: "Chiba Chiba",
        type: 'Kỹ Năng',
        desc: 'Biên Niên Ký Thất Nghiệp – cuốn sách có đầy đủ những ác mộng tệ nhất của bạn. Nhưng với ngòi bút của tác giả Chiba Chiba, thất nghiệp hiện ra tuy vất vả nhưng không hề não nề, bi lụy. Giọng văn giễu đời, tưởng chừng buông thả với cuộc sống nhưng luôn lạc quan một cách bình thản để sống....',
        status: 'Hoàn Thành',
    },
    {
        title: "Giữ Tâm Cho Sáng, Giữ Lòng Cho Yên",
        image: require('../../assets/Books/KyNang/giutam.jpg'),
        author: "Teruko Kobayashi",
        type: 'Kỹ Năng',
        desc: 'Đời người luôn biến đổi thăng trầm với mọi cung bậc cảm xúc hỉ, nộ, ái, ố. Ai cũng đôi lần hành xử nông nổi, nói những lời vô tâm làm tổn thương người khác hay rơi vào tuyệt vọng khi gặp khó khăn. Nhưng điều quan trọng là ta phải tự nhìn nhận lại mình, sửa chữa, tôi rèn bản thân và vững tâm tiếp tục tiến về phía trước để xây dựng mối quan hệ tốt đẹp hơn với bản thân và cả với người khác.',
        status: 'Hoàn Thành',
    },
    {
        title: "Hướng Nghiệp 4.0",
        image: require('../../assets/Books/KyNang/huongnghiep.jpg'),
        author: "Stage Designer",
        type: 'Kỹ Năng',
        desc: 'Kỉ nguyên 4.0 đã tạo ra những thay đổi sâu rộng trong sản xuất và đời sống, đặc biệt có những tác động không nhỏ đến sự chuyển dịch của các ngành nghề trong xã hội.',
        status: 'Hoàn Thành',
    },
    {
        title: "Làm Ít Được Nhiều",
        image: require('../../assets/Books/KyNang/lamitdcnhieu.jpg'),
        author: "Chin-Ning Chu",
        type: 'Kỹ Năng',
        desc: 'Trong thời đại thay đổi nhanh chóng và cạnh tranh gay gắt của chúng ta hiện nay, chúng ta thường tự vướng vào một quan điểm quá mệt mỏi là tin rằng thành công chỉ đến khi phải đánh đổi bằng sự cân bằng của cuộc sống.',
        status: 'Hoàn Thành',
    },
    {
        title: "Atomic Habits - Thay Đổi Tí Hon, Hiệu Quả Bất Ngờ",
        image: require('../../assets/Books/KyNang/thaydoitihon.jpg'),
        author: "James Clear",
        type: 'Kỹ Năng',
        desc: 'Atomic Habits - Thay Đổi Tí Hon, Hiệu Quả Bất Ngờ •  Wall Street Journal Bestseller, USA Today Bestseller, Publisher\'s Weekly Bestseller •  Nằm trong Top 20 tựa sách thể loại non-fiction bán chạy và được tìm đọc nhiều nhất của Amazon suốt 40 tuần tính đến tháng 9/2019 Một...',
        status: 'Hoàn Thành',
    },
    {
        title: "Trở Về Không - Trải Nghiệm Ho'oponopono",
        image: require('../../assets/Books/KyNang/trovekhong.jpg'),
        author: "Joe Vitale",
        type: 'Kỹ Năng',
        desc: 'Nếu Không giới hạn (Zero Limit) là sự bắt đầu của phương pháp Ho\'oponopono thì Trở về không (At Zero) chính là sự nối tiếp thông điệp với những phương thức nâng cao bí truyền, mở đường cho phép mầu xảy đến trong thực tại.',
        status: 'Hoàn Thành',
    },
    {
        title: "Hiểu Về Trái Tim",
        image: require('../../assets/Books/KyNang/hieutraitim.jpg'),
        author: "Minh Niệm",
        type: 'Kỹ Năng',
        desc: 'Hiểu Về Trái Tim Hiểu Về Trái Tim là một cuốn sách đặc biệt được viết bởi thiền sư Minh Niệm. Với phong thái và lối hành văn gần gũi với những sinh hoạt của người Việt, thầy Minh Niệm đã thật sự thổi hồn Việt vào cuốn sách nhỏ này.',
        status: 'Hoàn Thành',
    },
    {
        title: "Sức Mạnh Của Sự Tử Tế",
        image: require('../../assets/Books/KyNang/sucmanh.jpg'),
        author: "Linda Kaplan Thaler",
        type: 'Kỹ Năng',
        desc: 'Trong kinh doanh, tử tế không có nghĩa là thiếu quyết đoán hay cả nể… chẳng dễ mà thành được người tử tế, nhưng một khi đã được rồi thì bạn sẽ: - Nổi trội hơn - Kiếm được nhiều tiền hơn - Vui hơn - Khỏe mạnh hơn - Sống lâu hơn để tận hưởng bốn điều kể trên...',
        status: 'Hoàn Thành',
    },
    {
        title: "Đắc Nhân Tâm",
        image: require('../../assets/Books/KyNang/dacnhantam.jpg'),
        author: "Dale Carnegie",
        type: 'Kỹ Năng',
        desc: 'Đắc Nhân Tâm Đắc Nhân Tâm của Dale Carnegie là tác phẩm nổi tiếng nhất, bán chạy nhất và có tầm ảnh hưởng nhất của mọi thời đại. Cuốn sách đã được chuyển ngữ sang hầu hết các thứ tiếng trên thế giới và có mặt ở hàng trăm quốc gia. Đây là cuốn sách liên tục đứng đầu danh mục sách...',
        status: 'Hoàn Thành',
    },
]

export default SachKyNang