const SachKinhTe = [
    {
        title: "Dạy Con Làm Giàu",
        image: require('../../assets/Books/KinhTe/dayconlamgiau.jpg'),
        author: "Robert T. Kiyosaki",
        type: 'Kinh Tế',
        desc: 'Nếu bạn đã từng cảm thấy thất vọng vì việc làm công lãnh lương hay làm tư không cho bạn sự an toàn tài chính mà bạn khao khát , còn có cách thay thế. Nếu những đầu tư của bạn thất bại, bạn mệt mỏi vì những lời khuyên tài chính cũ xì, bạn lo lắng về việc nghỉ hưu, hay bạn chỉ dành nhiều thời gian hơn cho gia đình, bạn có thể tìm thấy con đường đến sự tự do về tài chính trong quyển sách này. Quyển sách gồm các câu chuyện thành công của những người đã đón nhận lời khuyên của người bố giàu và sau đó tìm thấy con đường đi đến sự thành công về tài chính của riêng mình. Và bạn cũng có thể tạo ra những câu chuyện thành công từ tập sách này',
        status: 'Hoàn Thành',
    },
    {
        title: "Hướng Dẫn Giao Dịch Theo Sóng Elliott",
        image: require('../../assets/Books/KinhTe/elliott.jpg'),
        author: "Jeffrey Kennedy",
        type: 'Kinh Tế',
        desc: 'Chào mừng các bạn! Hướng Dẫn Giao Dịch Theo Sóng Elliott là cuốn sách phải đọc dành cho những ai muốn biết cách thức giao dịch theo Nguyên Lý Sóng Elliott. Bạn sẽ biết làm thế nào để tìm ra các cơ hội giao dịch tốt, đánh giá chất lượng từng tín hiệu giao dịch, cách mở vị thế, quản trị giao dịch bằng cách nâng và hạ lệnh dừng lỗ, cũng như cách đóng lệnh hợp lý nhất',
        status: 'Hoàn Thành',
    },
    {
        title: "Kiếm Tiền Thời Khủng Hoảng",
        image: require('../../assets/Books/KinhTe/kiemtien.jpg'),
        author: "Martin D. Weiss",
        type: 'Kinh Tế',
        desc: 'Hiện nay, “khủng hoảng” có lẽ là từ được nhắc đến nhiều nhất, nó xuất hiện trên tất cả các phương tiện thông tin đại chúng, len lỏi vào cả những câu chuyện trong bữa cơm gia đình. Khủng hoảng ảnh hưởng mạnh mẽ không chỉ đến nền kinh tế vĩ mô của một đất nước, quốc gia mà còn tác động đến cuộc sống của từng người. Người ta coi khủng hoảng như một cơn bão quét, đặt chân đến đâu sẽ cuốn theo tài sản, sự yên ổn đến đó. Trong cơn bão “khủng hoảng” đó, dù ít hay nhiều, ai cũng sẽ phải gánh chịu tổn thất',
        status: 'Hoàn Thành',
    },
    {
        title: "Nghỉ Lớn Để Thành Công",
        image: require('../../assets/Books/KinhTe/nghilon.jpg'),
        author: "Donald Trump",
        type: 'Kinh Tế',
        desc: 'Sự sáng tạo là một trong những yếu tố rất quan trọng để thành công, bất kể công việc của bạn là gì đi chăng nữa. Bill Zanker là một người có óc sáng tạo và anh ấy biết cách tận dụng nó để đạt được hiệu quả cao nhất trong công việc. Đó là một nhà tổ chức tài ba. Quan điểm tích cực của Bill...',
        status: 'Hoàn Thành',
    },
    {
        title: "Cẩm Nang Đầu Tư Và Quản Lý Tài Chính Cá Nhân",
        image: require('../../assets/Books/KinhTe/quanlytaichinh.jpg'),
        author: "Phương Sĩ Duy",
        type: 'Kinh Tế',
        desc: 'Kỹ năng tối ưu hóa hiệu quả đầu tư với quy tắc “Tam giác vàng quản lý tài chính',
        status: 'Hoàn Thành',
    },
    {
        title: "Hướng Dẫn Thiết Lập Farmstay",
        image: require('../../assets/Books/KinhTe/farmstay.jpg'),
        author: "Phạm Thanh Tùng",
        type: 'Kinh Tế',
        desc: 'Đây là cuốn sách đầu tiên tại Việt Nam viết về Farmstay và cũng là cuốn sách hệ thống kiến thức chuẩn xác nhất cho những ai khao khát khởi nghiệp. Hướng Dẫn Thiết Lập Farmstay là cuốn sách được dịch từ cuốn sách “Farmstay Manual” của Học viện Nông nghiệp bền vững Minnesota Mỹ.',
        status: 'Hoàn Thành',
    },
    {
        title: "25 Năm Theo Dòng Kinh Tế Việt Nam",
        image: require('../../assets/Books/KinhTe/25namkinhte.jpg'),
        author: "Huỳnh Bửu Sơn",
        type: 'Kinh Tế',
        desc: 'Hai mươi lăm năm theo dòng kinh tế Việt Nam - đó cũng là thời gian mà tác giả Huỳnh Bửu Sơn - chuyên gia kinh tế - với tư cách người cầm bút đã ghi lại những trải nghiệm sống động và biết bao trăn trở của một trí thức từ ngày đất nước đổi mới.',
        status: 'Hoàn Thành',
    },
    {
        title: "Nền Kinh Tế Xanh Lam",
        image: require('../../assets/Books/KinhTe/blueeco.jpg'),
        author: "Gunter Pauli",
        type: 'Kinh Tế',
        desc: 'Quyển The Blue Economy cho thấy việc bảo đảm nguyên vật liệu và điều chỉnh các kế hoạch sản xuất theo kiểu mẫu của tự nhiên sẽ giải quyết được nhiều vấn đề suy thoái và ô nhiễm môi trường. Tuy nhiên, chính sách kinh tế hiện nay và các mô hình kinh doanh cốt lõi đã phớt lờ đi những giải pháp...',
        status: 'Hoàn Thành',
    },
    {
        title: "Người Giải Mã Thị Trường Tài Chính",
        image: require('../../assets/Books/KinhTe/nguoigiaima.jpg'),
        author: "Gregory Zuckerman",
        type: 'Kinh Tế',
        desc: 'Người Giải Mã Thị Trường Tài Chính. Simons và nhóm của ông ấy là một trong những nhà giao dịch bí ẩn nhất mà Phố Wall đã từng có. Họ không để lại bất cứ một dấu vết nào về cách họ chinh phục thị trường tài chính, để các đối thủ không nắm được bất kỳ manh mối nào. Viết về Simons và...',
        status: 'Hoàn Thành',
    },
    {
        title: "Gã Nghiện Giày - Tự Truyện Của Nhà Sáng Lập Nike",
        image: require('../../assets/Books/KinhTe/ganghiengiay.jpg'),
        author: "Phil Knight",
        type: 'Kinh Tế',
        desc: 'Gã Nghiện Giày - Tự Truyện Của Nhà Sáng Lập Nike Một câu chuyện cuốn hút, và truyền cảm hứng.... 24 tuổi, lấy bằng MBA ở Đại học Stanford, trăn trở với những câu hỏi lớn của cuộc đời, băn khoăn không biết tiếp tục làm việc cho một tập đoàn lớn hay tạo dựng sư nghiệp riêng cho...',
        status: 'Hoàn Thành',
    },
]

export default SachKinhTe