const SachVanHoc = [
  {
    title: 'Nếu Biết Trăm Năm Là Hữu Hạn',
    image: require('../../assets/Books/VanHoc/neubiet.jpg'),
    author: 'Phạm Lữ Ân',
    type: 'Văn Học',
    desc: 'Nếu biết trăm năm là hữu hạn, cớ gì ta không sống thật sâu...Có đôi khi những bộn bề của cuộc sống cuốn ta đi như dòng nước hững hờ cuốn trôi chiếc lá. Cứ thế, ta vội vã làm, vội vã ăn, vội vã ngủ, vội vã yêu và vội vã… để sống! Chắc hẳn đã không ít lần mỗi chúng ta đều thốt lên “giá như…',
    status: 'Hoàn Thành',
  },
  {
    title: 'Người Trồng Rừng',
    image: require('../../assets/Books/VanHoc/nguoitrong.jpg'),
    author: 'Jean Giono',
    type: 'Văn Học',
    desc: 'Sự sống có mặt là nhờ sự kết hợp chặt chẽ của biết bao yếu tố đến từ muôn nơi, từ cả vũ trụ và muôn người, muôn loài. Có ý thức sáng tỏ ấy, ta mới đem hết tâm ý đóng góp phần tốt nhất và đẹp nhất của mình để bảo vệ sự sống, bảo vệ thiên nhiên và muôn người, muôn loài.',
    status: 'Hoàn Thành',
  },
  {
    title: 'Papillon Người Tù Khổ Sai',
    image: require('../../assets/Books/VanHoc/papilon.jpg'),
    author: 'Henri Charriere',
    type: 'Văn Học',
    desc: 'Papillon Người Tù Khổ Sai là một thiên hồi kí của Henri Charrière kể lại chính cuộc đời mình, về hành trình từ khi bị bắt giam và xử án đầy khổ sai chung thân vì tội giết người theo lời khai của một nhân chứng đã được “dàn xếp” trước',
    status: 'Hoàn Thành',
  },
  {
    title: 'Spy Room: Lớp Học Điệp Viên',
    image: require('../../assets/Books/VanHoc/spyroom.jpg'),
    author: 'Takemachi',
    type: 'Văn Học',
    desc: 'Spy room – Lớp học điệp viên (tên gốc: Spy kyoushitsu) là series light novel độc đáo về thể loại điệp viên, tình báo vốn rất hiếm hoi trong dòng manga/light novel, là cái tên xuất sắc đã giành giải nhất giải thưởng thường niên của Fantasia Bunko lần thứ 32',
    status: 'Hoàn Thành',
  },
  {
    title: 'Trong Đáy Mắt Trời Xanh Là Vĩnh Viễn',
    image: require('../../assets/Books/VanHoc/xuanquynh.jpg'),
    author: 'Xuân Quỳnh',
    type: 'Văn Học',
    desc: 'Nhân dịp kỷ niệm 80 năm ngày sinh của Xuân Quỳnh, Trong Đáy Mắt Trời Xanh Là Vĩnh Viễn ra mắt độc giả để tưởng nhớ và tri ân nữ thi sĩ tài hoa đã có những đóng góp lớn cho nền văn học Việt Nam hiện đại.',
    status: 'Hoàn Thành',
  },
  {
    title: 'Truyện Kiều Văn Xuôi (Dành Cho Người Trẻ)',
    image: require('../../assets/Books/VanHoc/truyenkieu.jpg'),
    author: 'Thích Nhất Hạnh',
    type: 'Văn Học',
    desc: 'Truyện Kiều Văn Xuôi Truyện Kiều là tác phẩm thơ nổi tiếng nhất của nền Thi ca Việt Nam. Người trẻ nào trong thời gian học Trung học cũng có dịp được nghe về Truyện Kiều và học một ít về Truyện Kiều. Nhưng vì Truyện Kiều là một tác phẩm cổ điển và lại có nhiều điển tích cho nên đối...',
    status: 'Hoàn Thành',
  },
  {
    title: 'Cây Cam Ngọt Của Tôi',
    image: require('../../assets/Books/VanHoc/caycamngot.jpg'),
    author: 'José Mauro de Vasconcelos',
    type: 'Văn Học',
    desc: 'Hãy làm quen với Zezé, cậu bé tinh nghịch siêu hạng đồng thời cũng đáng yêu bậc nhất, với ước mơ lớn lên trở thành nhà thơ cổ thắt nơ bướm. Chẳng phải ai cũng công nhận khoản “đáng yêu” kia đâu nhé. Bởi vì, ở cái xóm ngoại ô nghèo ấy, nỗi khắc khổ bủa vây đã che mờ mắt người ta trước trái tim...',
    status: 'Hoàn Thành',
  },
  {
    title: 'Nữ Sinh',
    image: require('../../assets/Books/VanHoc/nusinh.jpg'),
    author: 'Dazai Osamu',
    type: 'Văn Học',
    desc: 'Hầu hết các truyện trong tuyển tập đều có nhân vật chính là nữ với những miêu tả tâm lý hết sức tinh tế và cao sang. Không những thành công với thể loại tự truyện tư tiểu thuyết, Dazai còn chứng tỏ bản lĩnh bậc thầy của mình trong việc am hiểu tâm lý phụ nữ xứ Phù Tang. Qua tác phẩm của Dazai,...',
    status: 'Hoàn Thành',
  },
  {
    title: 'Tâm Thành Và Lộc Đời',
    image: require('../../assets/Books/VanHoc/tamthanhloc.jpg'),
    author: 'Thành Lộc',
    type: 'Văn Học',
    desc: 'Tâm Thành Và Lộc Đời Đã có rải rác vài lời đề nghị tôi viết hồi ký hoặc ngồi kể cho người ta ghi lại từ nhiều năm trước nhưng tôi đã từ chối bai bải... vì thấy mình chưa đủ độ dầy và độ... sạch sẽ để cho người ta đọc về mình, phần cũng lười lắm nên thôi...',
    status: 'Hoàn Thành',
  },
  {
    title: 'Công Ty Cung Cấp Yêu Tinh',
    image: require('../../assets/Books/VanHoc/yeutinh.jpg'),
    author: 'Hoshi Shinichi',
    type: 'Văn Học',
    desc: 'Công Ty Cung Cấp Yêu Tinh Tác phẩm của Hoshi Shinichi tuy ngắn gọn và mang nhiều tính chất giả tưởng nhưng chủ yếu là mượn xưa để nói nay, mượn huyễn để độ chân, cho chúng ta nhiều bài học thâm thúy về cuộc sống và bản chất con người. Sự thông minh và từng trải của tác giả khiến cho...',
    status: 'Hoàn Thành',
  },
]

export default SachVanHoc
