export const IconString = {
    goBack: "chevron-back-outline",
    goForward: "chevron-forward-outline",
    arrowForward: "arrow-forward-circle-outline",
    heart: 'heart',
    comment: 'chatbubble-ellipses-outline',
    share: 'share-outline',
    search: 'search',
    menu: "menu-outline",
    checkmark: "checkmark-outline",
    checkmarkCircle: "checkmark-circle-outline",
    moon: 'moon',
    sun: 'sunny',
    close: "close-outline",
    send: "send",
    showPass: "eye",
    hiddenPass: "eye-off",
    edit: "create",
    filter: 'filter-outline',
    delete: "trash-outline",
    mail: 'mail',
    alarm: "alarm-outline",
    user: 'person',
    book: 'book',
    chatBubble: 'chatbubble-ellipses',
    logOut: 'log-out',
    goToTop: 'arrow-up-circle-outline',
    reset: 'refresh-outline',


    //Navigation Icon
    homeFill: 'home',
    userCircleFill: 'person-circle',
    categoryFill: 'apps',
    homeOutline: 'home-outline',
    userCircleOutline: 'person-circle-outline',
    categoryOutline: 'apps-outline',
}